name: MCCMF
main: MCCMF.Main.Main
version: 1.0
author: RealQPixel
softdepend: [MultiChatBridge]

commands:
    core:
      description: The Core Command

    giveitem:
          usage:/<command>
          description: giveitem command

